# Generated by Django 5.0.6 on 2024-06-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(db_column='id_comuna', primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idSexo', models.AutoField(db_column='id_sexo', primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('profesion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('idComuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='contacto.comuna')),
                ('idSexo', models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.CASCADE, to='contacto.sexo')),
            ],
        ),
    ]
